export const CONNECT_TO_COINMARKETCAP_API = 'CONNECT_TO_COINMARKETCAP_API';
export const GET_COIN_METADATA = 'GET_COIN_METADATA';
export const SAVE_USER_TRANSACTIONS = 'SAVE_USER_TRANSACTIONS';
export const SAVE_USER_WALLET_INFO = 'SAVE_USER_WALLET_INFO';
